services:
  jmooredev2:
    build: .
    container_name: jmoore.dev.2
    restart: unless-stopped
    ports:
      - "18235:18235"
    volumes:
      - ./uploads:/opt/jmoore.dev.2/uploads/
    tty: true
    environment:
      - NODE_ENV=production
